#!/usr/bin/env python3
"""Risikoprofil – definiert 5 Tiers und Risk→Parameter Mapping."""
import math

# ─── 5 Aktien-Tiers ──────────────────────────────────────────
# Tier 0 = defensiv (Blue Chips, Utilities, REITs, Healthcare)
# Tier 1 = balanced (Large-Cap Tech, Finance, Industrie)
# Tier 2 = growth (Mid-Cap, Biotech, Cloud, Consumer Disc.)
# Tier 3 = speculative (Meme, Crypto, EV, Space, China)
# Tier 4 = ETFs/heavily leveraged (3x Bull/Bear, Volatility, Crypto)

TIERS = {
    0: [
        "KO", "PEP", "PG", "CL", "KMB", "K", "CPB", "CAG", "GIS", "HRL", "SJM", "MKC",
        "TSN", "ADM", "BG", "KHC", "MDLZ", "HSY", "SYY", "DEO", "BF-B", "COTY", "IP", "CCK",
        "GPK", "DUK", "SO", "NEE", "D", "AEP", "EXC", "ED", "XEL", "PPL", "PEG", "FE",
        "AEE", "ETR", "WEC", "CMS", "CNP", "SRE", "EIX", "AWK", "ES", "LNT", "IDA", "ATO",
        "EVRG", "PNW", "OTTR", "POR", "NWE", "HE", "O", "PLD", "AMT", "EQIX", "DLR", "WELL",
        "SPG", "PSA", "AVB", "EQR", "BXP", "ARE", "KIM", "REG", "FRT", "NNN", "WPC", "CUBE",
        "EXR", "SUI", "ELS", "AMH", "INVH", "MAA", "CPT", "UDR", "ESS", "JNJ", "ABT", "BMY",
        "MRK", "PFE", "ABBV", "LLY", "TMO", "DHR", "UNH", "CVS", "CI", "HUM", "ELV", "MDT",
        "SYK", "BSX", "ZBH", "BDX", "ISRG", "EW", "RMD", "DXCM", "WST", "COO", "TFX", "ATR",
        "BAX", "ALC", "WMT", "COST", "TGT", "DG", "DLTR", "KR", "ACI", "CALM", "NEM", "GOLD",
        "ABX", "KGC", "AGI", "FNV", "WPM", "RGLD"
    ],
    1: [
        "AAPL", "MSFT", "GOOGL", "AMZN", "META", "NVDA", "ORCL", "IBM", "CSCO", "INTC", "QCOM", "TXN",
        "AVGO", "AMD", "MU", "LRCX", "AMAT", "KLAC", "NXPI", "SWKS", "STM", "ADI", "MCHP", "CDNS",
        "SNPS", "JPM", "GS", "MS", "BAC", "WFC", "C", "V", "MA", "AXP", "COF", "SYF",
        "PYPL", "XYZ", "BLK", "SCHW", "IBKR", "MCO", "SPGI", "ICE", "CME", "NDAQ", "MKTX", "CBOE",
        "BRK-B", "MET", "PRU", "AFL", "MMC", "AON", "AJG", "BRO", "WTW", "CB", "ALL", "TRV",
        "PGR", "HIG", "CINF", "CAT", "DE", "GE", "HON", "BA", "LMT", "RTX", "NOC", "GD",
        "TDG", "TXT", "COL", "MMM", "EMR", "ROK", "ETN", "IR", "ITW", "DOV", "PH", "CARR",
        "OTIS", "JCI", "TT", "AME", "ROP", "HWM", "UNP", "UPS", "FDX", "CSX", "NSC", "CNI",
        "CP", "JBHT", "ODFL", "CHRW", "EXPD", "XPO", "WM", "RSG", "WCN", "STE", "ECL", "CHD",
        "VZ", "T", "TMUS", "CMCSA", "CHTR", "CABO", "LUMN", "CCI", "SBAC", "CROX", "LHX", "BWXT",
        "HII", "SAIC", "LDOS", "LIN", "APD", "SHW", "PPG", "DD", "DOW", "LYB", "NUE", "STLD",
        "CLF", "X", "FCX", "SCCO", "AA", "CENX", "AVY", "BALL", "SLGN"
    ],
    2: [
        "DDOG", "CRWD", "ZS", "NET", "OKTA", "PANW", "FTNT", "CHKP", "VRSN", "WDAY", "NOW", "TEAM",
        "MDB", "ESTC", "GTLB", "PATH", "AI", "PLTR", "SOFI", "SNAP", "PINS", "UBER", "DASH", "COIN",
        "RBLX", "SHOP", "ROKU", "ZM", "DOCU", "BOX", "WK", "DOMO", "DT", "FICO", "INTU", "ADSK",
        "CTSH", "INFY", "WIT", "ACN", "EPAM", "GLPI", "AMGN", "GILD", "BIIB", "REGN", "VRTX", "MRNA",
        "BHVN", "EXEL", "ALKS", "ILMN", "ALNY", "INCY", "UTHR", "SRPT", "HALO", "MGNX", "HD", "LOW",
        "NKE", "SBUX", "MCD", "YUM", "DPZ", "CMG", "QSR", "WING", "SHAK", "TXRH", "TJX", "ROST",
        "BURL", "AEO", "ANF", "URBN", "KSS", "M", "DDS", "DHI", "LEN", "PHM", "NVR", "TOL",
        "KBH", "LGI", "MTH", "BECN", "BKNG", "EXPE", "ABNB", "TRIP", "TCOM", "MMYT", "KTOS", "AVAV",
        "WWD", "HEI", "SUM", "MLM", "VMC", "EXP", "TREX", "FND", "BLD", "FIX", "SEDG", "ENPH",
        "RUN", "JKS", "ARRY", "BE", "PLUG", "FCEL", "PODD", "TNDM", "GH", "SGRY", "PRVA", "ALGN"
    ],
    3: [
        "GME", "AMC", "KOSS", "TLRY", "CGC", "ACB", "SNDL", "CRON", "VFF", "MARA", "RIOT", "CLSK",
        "WULF", "HIVE", "CIFR", "BTBT", "CORZ", "IREN", "CAN", "LCID", "RIVN", "WKHS", "XPEV", "NIO",
        "LI", "PSNY", "QS", "SLDP", "MVST", "HYLN", "BLBD", "GGR", "TPIC", "CRSP", "NTLA", "EDIT",
        "BEAM", "PRME", "FATE", "ALLO", "CRBU", "DNLI", "BCRX", "IMRX", "VXRT", "ASRT", "SENS", "BIOC",
        "JAGX", "CVM", "PRTA", "HOOD", "UPST", "AFRM", "CHWY", "BROS", "FIGS", "PENN", "DKNG", "FLTR",
        "MELI", "SE", "NU", "RELY", "STNE", "DLO", "NIBE", "LMND", "TREE", "UWMC", "U", "MTTR",
        "CRSR", "LOGI", "HEAR", "GPRO", "SPCE", "ASTS", "RDW", "RKLB", "GSAT", "IRDM", "SES", "GEO",
        "ASTC", "MDA", "BB", "FUBO", "JOBY", "ACHR", "EH", "NNOX", "SESN", "AEHR", "BABA", "JD",
        "BIDU", "TME", "WB", "VIPS", "TDOC", "LVGO", "ONEM", "HLTH", "CERT", "YI", "GTBIF", "CRLBF",
        "PLNHF"
    ],
    4: [
        "TQQQ", "SOXL", "FAS", "LABU", "TECL", "FNGU", "NAIL", "DRN", "UBOT", "WEBL", "UPRO", "UDOW",
        "UMDD", "DPST", "JNUG", "NRGU", "BOIL", "UCO", "USLV", "BNKU", "SQQQ", "SOXS", "FNGD", "SRTY",
        "SPXU", "SDOW", "SPXS", "EDZ", "TZA", "DRV", "KOLD", "SCO", "JDST", "DUST", "ZSL", "GLL",
        "UVXY", "VIXY", "SVXY", "ZIV", "VXX", "VIXM", "VXZ", "USO", "UNG", "GLD", "SLV", "GDX",
        "GDXJ", "XME", "XLB", "PICK", "LIT", "REMX", "URA", "NLR", "DBA", "CORN", "WEAT", "SOYB",
        "COW", "CPER", "CAFE", "JO", "BAL", "NIB", "IBIT", "FBTC", "ARKB", "BITB", "GBTC", "BITO",
        "ETHA", "ETHU", "BTCI", "XLK", "XLP", "XLE", "XLV", "XLI", "XLF", "XLRE", "XLU", "XLC",
        "XLY", "VGT", "VDC", "VDE", "VHT", "VIS", "VFH", "VNQ", "VPU", "VAW", "VCR", "QQQ",
        "SPY", "DIA", "IWM", "IJR", "MDY", "VO", "VB", "VOO", "IVV", "VT", "VTI", "EEM",
        "VWO", "EFA", "VEA", "EWJ", "EWG", "EWQ", "EWU", "EWL", "EWA", "FXI", "KWEB", "EWZ",
        "RSX", "EPI", "INDA", "TUR", "ECH", "EIDO", "FLCH", "TLT", "IEF", "SHY", "AGG", "BND",
        "LQD", "HYG", "JNK", "MUB", "TFI", "ARKK", "ARKW", "ARKG", "ARKF", "ICLN", "TAN", "PBW",
        "SMH", "XSD", "ROBT", "BOTZ", "HACK", "CIBR", "FINX", "SKYY", "CLOU", "AIQ", "DRIV", "MILN",
        "WATER", "IYR", "REET", "SRET", "RWR", "SCHH", "FREL", "ROOF", "REZ", "SCHD", "VYM", "VIG",
        "DGRO", "DVY", "HDV", "SPYD", "DVN", "SDIV", "PEY", "IHF", "IBB", "XBI", "BBH", "PJP",
        "PPH", "IYH", "FHLC", "TIPS", "VTIP", "STIP", "FIPDX", "SCHP", "LTPZ", "WIP"
    ],
}

# ─── Ticker → Tier ───────────────────────────────────────────
TICKER_TO_TIER = {
    "AA": 1,
    "AAPL": 1,
    "ABBV": 0,
    "ABNB": 2,
    "ABT": 0,
    "ABX": 0,
    "ACB": 3,
    "ACHR": 3,
    "ACI": 0,
    "ACN": 2,
    "ADI": 1,
    "ADM": 0,
    "ADSK": 2,
    "AEE": 0,
    "AEHR": 3,
    "AEO": 2,
    "AEP": 0,
    "AFL": 1,
    "AFRM": 3,
    "AGG": 4,
    "AGI": 0,
    "AI": 2,
    "AIQ": 4,
    "AJG": 1,
    "ALC": 0,
    "ALGN": 2,
    "ALKS": 2,
    "ALL": 1,
    "ALLO": 3,
    "ALNY": 2,
    "AMAT": 1,
    "AMC": 3,
    "AMD": 1,
    "AME": 1,
    "AMGN": 2,
    "AMH": 0,
    "AMT": 0,
    "AMZN": 1,
    "ANF": 2,
    "AON": 1,
    "APD": 1,
    "ARE": 0,
    "ARKB": 4,
    "ARKF": 4,
    "ARKG": 4,
    "ARKK": 4,
    "ARKW": 4,
    "ARRY": 2,
    "ASRT": 3,
    "ASTC": 3,
    "ASTS": 3,
    "ATO": 0,
    "ATR": 0,
    "AVAV": 2,
    "AVB": 0,
    "AVGO": 1,
    "AVY": 1,
    "AWK": 0,
    "AXP": 1,
    "BA": 1,
    "BABA": 3,
    "BAC": 1,
    "BAL": 4,
    "BALL": 1,
    "BAX": 0,
    "BB": 3,
    "BBH": 4,
    "BCRX": 3,
    "BDX": 0,
    "BE": 2,
    "BEAM": 3,
    "BECN": 2,
    "BF-B": 0,
    "BG": 0,
    "BHVN": 2,
    "BIDU": 3,
    "BIIB": 2,
    "BIOC": 3,
    "BITB": 4,
    "BITO": 4,
    "BKNG": 2,
    "BLBD": 3,
    "BLD": 2,
    "BLK": 1,
    "BMY": 0,
    "BND": 4,
    "BNKU": 4,
    "BOIL": 4,
    "BOTZ": 4,
    "BOX": 2,
    "BRK-B": 1,
    "BRO": 1,
    "BROS": 3,
    "BSX": 0,
    "BTBT": 3,
    "BTCI": 4,
    "BURL": 2,
    "BWXT": 1,
    "BXP": 0,
    "C": 1,
    "CABO": 1,
    "CAFE": 4,
    "CAG": 0,
    "CALM": 0,
    "CAN": 3,
    "CARR": 1,
    "CAT": 1,
    "CB": 1,
    "CBOE": 1,
    "CCI": 1,
    "CCK": 0,
    "CDNS": 1,
    "CENX": 1,
    "CERT": 3,
    "CGC": 3,
    "CHD": 1,
    "CHKP": 2,
    "CHRW": 1,
    "CHTR": 1,
    "CHWY": 3,
    "CI": 0,
    "CIBR": 4,
    "CIFR": 3,
    "CINF": 1,
    "CL": 0,
    "CLF": 1,
    "CLOU": 4,
    "CLSK": 3,
    "CMCSA": 1,
    "CME": 1,
    "CMG": 2,
    "CMS": 0,
    "CNI": 1,
    "CNP": 0,
    "COF": 1,
    "COIN": 2,
    "COL": 1,
    "COO": 0,
    "CORN": 4,
    "CORZ": 3,
    "COST": 0,
    "COTY": 0,
    "COW": 4,
    "CP": 1,
    "CPB": 0,
    "CPER": 4,
    "CPT": 0,
    "CRBU": 3,
    "CRLBF": 3,
    "CRON": 3,
    "CROX": 1,
    "CRSP": 3,
    "CRSR": 3,
    "CRWD": 2,
    "CSCO": 1,
    "CSX": 1,
    "CTSH": 2,
    "CUBE": 0,
    "CVM": 3,
    "CVS": 0,
    "D": 0,
    "DASH": 2,
    "DBA": 4,
    "DD": 1,
    "DDOG": 2,
    "DDS": 2,
    "DE": 1,
    "DEO": 0,
    "DG": 0,
    "DGRO": 4,
    "DHI": 2,
    "DHR": 0,
    "DIA": 4,
    "DKNG": 3,
    "DLO": 3,
    "DLR": 0,
    "DLTR": 0,
    "DNLI": 3,
    "DOCU": 2,
    "DOMO": 2,
    "DOV": 1,
    "DOW": 1,
    "DPST": 4,
    "DPZ": 2,
    "DRIV": 4,
    "DRN": 4,
    "DRV": 4,
    "DT": 2,
    "DUK": 0,
    "DUST": 4,
    "DVN": 4,
    "DVY": 4,
    "DXCM": 0,
    "ECH": 4,
    "ECL": 1,
    "ED": 0,
    "EDIT": 3,
    "EDZ": 4,
    "EEM": 4,
    "EFA": 4,
    "EH": 3,
    "EIDO": 4,
    "EIX": 0,
    "ELS": 0,
    "ELV": 0,
    "EMR": 1,
    "ENPH": 2,
    "EPAM": 2,
    "EPI": 4,
    "EQIX": 0,
    "EQR": 0,
    "ES": 0,
    "ESS": 0,
    "ESTC": 2,
    "ETHA": 4,
    "ETHU": 4,
    "ETN": 1,
    "ETR": 0,
    "EVRG": 0,
    "EW": 0,
    "EWA": 4,
    "EWG": 4,
    "EWJ": 4,
    "EWL": 4,
    "EWQ": 4,
    "EWU": 4,
    "EWZ": 4,
    "EXC": 0,
    "EXEL": 2,
    "EXP": 2,
    "EXPD": 1,
    "EXPE": 2,
    "EXR": 0,
    "FAS": 4,
    "FATE": 3,
    "FBTC": 4,
    "FCEL": 2,
    "FCX": 1,
    "FDX": 1,
    "FE": 0,
    "FHLC": 4,
    "FICO": 2,
    "FIGS": 3,
    "FINX": 4,
    "FIPDX": 4,
    "FIX": 2,
    "FLCH": 4,
    "FLTR": 3,
    "FND": 2,
    "FNGD": 4,
    "FNGU": 4,
    "FNV": 0,
    "FREL": 4,
    "FRT": 0,
    "FTNT": 2,
    "FUBO": 3,
    "FXI": 4,
    "GBTC": 4,
    "GD": 1,
    "GDX": 4,
    "GDXJ": 4,
    "GE": 1,
    "GEO": 3,
    "GGR": 3,
    "GH": 2,
    "GILD": 2,
    "GIS": 0,
    "GLD": 4,
    "GLL": 4,
    "GLPI": 2,
    "GME": 3,
    "GOLD": 0,
    "GOOGL": 1,
    "GPK": 0,
    "GPRO": 3,
    "GS": 1,
    "GSAT": 3,
    "GTBIF": 3,
    "GTLB": 2,
    "HACK": 4,
    "HALO": 2,
    "HD": 2,
    "HDV": 4,
    "HE": 0,
    "HEAR": 3,
    "HEI": 2,
    "HIG": 1,
    "HII": 1,
    "HIVE": 3,
    "HLTH": 3,
    "HON": 1,
    "HOOD": 3,
    "HRL": 0,
    "HSY": 0,
    "HUM": 0,
    "HWM": 1,
    "HYG": 4,
    "HYLN": 3,
    "IBB": 4,
    "IBIT": 4,
    "IBKR": 1,
    "IBM": 1,
    "ICE": 1,
    "ICLN": 4,
    "IDA": 0,
    "IEF": 4,
    "IHF": 4,
    "IJR": 4,
    "ILMN": 2,
    "IMRX": 3,
    "INCY": 2,
    "INDA": 4,
    "INFY": 2,
    "INTC": 1,
    "INTU": 2,
    "INVH": 0,
    "IP": 0,
    "IR": 1,
    "IRDM": 3,
    "IREN": 3,
    "ISRG": 0,
    "ITW": 1,
    "IVV": 4,
    "IWM": 4,
    "IYH": 4,
    "IYR": 4,
    "JAGX": 3,
    "JBHT": 1,
    "JCI": 1,
    "JD": 3,
    "JDST": 4,
    "JKS": 2,
    "JNJ": 0,
    "JNK": 4,
    "JNUG": 4,
    "JO": 4,
    "JOBY": 3,
    "JPM": 1,
    "K": 0,
    "KBH": 2,
    "KGC": 0,
    "KHC": 0,
    "KIM": 0,
    "KLAC": 1,
    "KMB": 0,
    "KO": 0,
    "KOLD": 4,
    "KOSS": 3,
    "KR": 0,
    "KSS": 2,
    "KTOS": 2,
    "KWEB": 4,
    "LABU": 4,
    "LCID": 3,
    "LDOS": 1,
    "LEN": 2,
    "LGI": 2,
    "LHX": 1,
    "LI": 3,
    "LIN": 1,
    "LIT": 4,
    "LLY": 0,
    "LMND": 3,
    "LMT": 1,
    "LNT": 0,
    "LOGI": 3,
    "LOW": 2,
    "LQD": 4,
    "LRCX": 1,
    "LTPZ": 4,
    "LUMN": 1,
    "LVGO": 3,
    "LYB": 1,
    "M": 2,
    "MA": 1,
    "MAA": 0,
    "MARA": 3,
    "MCD": 2,
    "MCHP": 1,
    "MCO": 1,
    "MDA": 3,
    "MDB": 2,
    "MDLZ": 0,
    "MDT": 0,
    "MDY": 4,
    "MELI": 3,
    "MET": 1,
    "META": 1,
    "MGNX": 2,
    "MILN": 4,
    "MKC": 0,
    "MKTX": 1,
    "MLM": 2,
    "MMC": 1,
    "MMM": 1,
    "MMYT": 2,
    "MRK": 0,
    "MRNA": 2,
    "MS": 1,
    "MSFT": 1,
    "MTH": 2,
    "MTTR": 3,
    "MU": 1,
    "MUB": 4,
    "MVST": 3,
    "NAIL": 4,
    "NDAQ": 1,
    "NEE": 0,
    "NEM": 0,
    "NET": 2,
    "NIB": 4,
    "NIBE": 3,
    "NIO": 3,
    "NKE": 2,
    "NLR": 4,
    "NNN": 0,
    "NNOX": 3,
    "NOC": 1,
    "NOW": 2,
    "NRGU": 4,
    "NSC": 1,
    "NTLA": 3,
    "NU": 3,
    "NUE": 1,
    "NVDA": 1,
    "NVR": 2,
    "NWE": 0,
    "NXPI": 1,
    "O": 0,
    "ODFL": 1,
    "OKTA": 2,
    "ONEM": 3,
    "ORCL": 1,
    "OTIS": 1,
    "OTTR": 0,
    "PANW": 2,
    "PATH": 2,
    "PBW": 4,
    "PEG": 0,
    "PENN": 3,
    "PEP": 0,
    "PEY": 4,
    "PFE": 0,
    "PG": 0,
    "PGR": 1,
    "PH": 1,
    "PHM": 2,
    "PICK": 4,
    "PINS": 2,
    "PJP": 4,
    "PLD": 0,
    "PLNHF": 3,
    "PLTR": 2,
    "PLUG": 2,
    "PNW": 0,
    "PODD": 2,
    "POR": 0,
    "PPG": 1,
    "PPH": 4,
    "PPL": 0,
    "PRME": 3,
    "PRTA": 3,
    "PRU": 1,
    "PRVA": 2,
    "PSA": 0,
    "PSNY": 3,
    "PYPL": 1,
    "QCOM": 1,
    "QQQ": 4,
    "QS": 3,
    "QSR": 2,
    "RBLX": 2,
    "RDW": 3,
    "REET": 4,
    "REG": 0,
    "REGN": 2,
    "RELY": 3,
    "REMX": 4,
    "REZ": 4,
    "RGLD": 0,
    "RIOT": 3,
    "RIVN": 3,
    "RKLB": 3,
    "RMD": 0,
    "ROBT": 4,
    "ROK": 1,
    "ROKU": 2,
    "ROOF": 4,
    "ROP": 1,
    "ROST": 2,
    "RSG": 1,
    "RSX": 4,
    "RTX": 1,
    "RUN": 2,
    "RWR": 4,
    "SAIC": 1,
    "SBAC": 1,
    "SBUX": 2,
    "SCCO": 1,
    "SCHD": 4,
    "SCHH": 4,
    "SCHP": 4,
    "SCHW": 1,
    "SCO": 4,
    "SDIV": 4,
    "SDOW": 4,
    "SE": 3,
    "SEDG": 2,
    "SENS": 3,
    "SES": 3,
    "SESN": 3,
    "SGRY": 2,
    "SHAK": 2,
    "SHOP": 2,
    "SHW": 1,
    "SHY": 4,
    "SJM": 0,
    "SKYY": 4,
    "SLDP": 3,
    "SLGN": 1,
    "SLV": 4,
    "SMH": 4,
    "SNAP": 2,
    "SNDL": 3,
    "SNPS": 1,
    "SO": 0,
    "SOFI": 2,
    "SOXL": 4,
    "SOXS": 4,
    "SOYB": 4,
    "SPCE": 3,
    "SPG": 0,
    "SPGI": 1,
    "SPXS": 4,
    "SPXU": 4,
    "SPY": 4,
    "SPYD": 4,
    "SQQQ": 4,
    "SRE": 0,
    "SRET": 4,
    "SRPT": 2,
    "SRTY": 4,
    "STE": 1,
    "STIP": 4,
    "STLD": 1,
    "STM": 1,
    "STNE": 3,
    "SUI": 0,
    "SUM": 2,
    "SVXY": 4,
    "SWKS": 1,
    "SYF": 1,
    "SYK": 0,
    "SYY": 0,
    "T": 1,
    "TAN": 4,
    "TCOM": 2,
    "TDG": 1,
    "TDOC": 3,
    "TEAM": 2,
    "TECL": 4,
    "TFI": 4,
    "TFX": 0,
    "TGT": 0,
    "TIPS": 4,
    "TJX": 2,
    "TLRY": 3,
    "TLT": 4,
    "TME": 3,
    "TMO": 0,
    "TMUS": 1,
    "TNDM": 2,
    "TOL": 2,
    "TPIC": 3,
    "TQQQ": 4,
    "TREE": 3,
    "TREX": 2,
    "TRIP": 2,
    "TRV": 1,
    "TSN": 0,
    "TT": 1,
    "TUR": 4,
    "TXN": 1,
    "TXRH": 2,
    "TXT": 1,
    "TZA": 4,
    "U": 3,
    "UBER": 2,
    "UBOT": 4,
    "UCO": 4,
    "UDOW": 4,
    "UDR": 0,
    "UMDD": 4,
    "UNG": 4,
    "UNH": 0,
    "UNP": 1,
    "UPRO": 4,
    "UPS": 1,
    "UPST": 3,
    "URA": 4,
    "URBN": 2,
    "USLV": 4,
    "USO": 4,
    "UTHR": 2,
    "UVXY": 4,
    "UWMC": 3,
    "V": 1,
    "VAW": 4,
    "VB": 4,
    "VCR": 4,
    "VDC": 4,
    "VDE": 4,
    "VEA": 4,
    "VFF": 3,
    "VFH": 4,
    "VGT": 4,
    "VHT": 4,
    "VIG": 4,
    "VIPS": 3,
    "VIS": 4,
    "VIXM": 4,
    "VIXY": 4,
    "VMC": 2,
    "VNQ": 4,
    "VO": 4,
    "VOO": 4,
    "VPU": 4,
    "VRSN": 2,
    "VRTX": 2,
    "VT": 4,
    "VTI": 4,
    "VTIP": 4,
    "VWO": 4,
    "VXRT": 3,
    "VXX": 4,
    "VXZ": 4,
    "VYM": 4,
    "VZ": 1,
    "WATER": 4,
    "WB": 3,
    "WCN": 1,
    "WDAY": 2,
    "WEAT": 4,
    "WEBL": 4,
    "WEC": 0,
    "WELL": 0,
    "WFC": 1,
    "WING": 2,
    "WIP": 4,
    "WIT": 2,
    "WK": 2,
    "WKHS": 3,
    "WM": 1,
    "WMT": 0,
    "WPC": 0,
    "WPM": 0,
    "WST": 0,
    "WTW": 1,
    "WULF": 3,
    "WWD": 2,
    "X": 1,
    "XBI": 4,
    "XEL": 0,
    "XLB": 4,
    "XLC": 4,
    "XLE": 4,
    "XLF": 4,
    "XLI": 4,
    "XLK": 4,
    "XLP": 4,
    "XLRE": 4,
    "XLU": 4,
    "XLV": 4,
    "XLY": 4,
    "XME": 4,
    "XPEV": 3,
    "XPO": 1,
    "XSD": 4,
    "XYZ": 1,
    "YI": 3,
    "YUM": 2,
    "ZBH": 0,
    "ZIV": 4,
    "ZM": 2,
    "ZS": 2,
    "ZSL": 4,
}

# ─── Ticker → Name (für Dashboard-Fallback) ───────────────────
TICKER_NAMES = {
    "AA": "AA [Basic Materials]",
    "AAPL": "AAPL [Technology]",
    "ABBV": "ABBV [Healthcare]",
    "ABNB": "ABNB [Consumer Cyclical]",
    "ABT": "ABT [Healthcare]",
    "ABX": "ABX [Financial Services]",
    "ACB": "ACB [Healthcare]",
    "ACHR": "ACHR [Industrials]",
    "ACI": "ACI [Consumer Defensive]",
    "ACN": "ACN [Technology]",
    "ADI": "ADI [Technology]",
    "ADM": "ADM [Consumer Defensive]",
    "ADSK": "ADSK [Technology]",
    "AEE": "AEE [Utilities]",
    "AEHR": "AEHR [Technology]",
    "AEO": "AEO [Consumer Cyclical]",
    "AEP": "AEP [Utilities]",
    "AFL": "AFL [Financial Services]",
    "AFRM": "AFRM [Financial Services]",
    "AGG": "AGG – ETF/Hebel",
    "AGI": "AGI [Basic Materials]",
    "AI": "AI [Technology]",
    "AIQ": "AIQ – ETF/Hebel",
    "AJG": "AJG [Financial Services]",
    "ALC": "ALC [Healthcare]",
    "ALGN": "ALGN [Healthcare]",
    "ALKS": "ALKS [Healthcare]",
    "ALL": "ALL [Financial Services]",
    "ALLO": "ALLO [Healthcare]",
    "ALNY": "ALNY [Healthcare]",
    "AMAT": "AMAT [Technology]",
    "AMC": "AMC [Communication Services]",
    "AMD": "AMD [Technology]",
    "AME": "AME [Industrials]",
    "AMGN": "AMGN [Healthcare]",
    "AMH": "AMH [Real Estate]",
    "AMT": "AMT [Real Estate]",
    "AMZN": "AMZN [Consumer Cyclical]",
    "ANF": "ANF [Consumer Cyclical]",
    "AON": "AON [Financial Services]",
    "APD": "APD [Basic Materials]",
    "ARE": "ARE [Real Estate]",
    "ARKB": "ARKB – ETF/Hebel",
    "ARKF": "ARKF – ETF/Hebel",
    "ARKG": "ARKG – ETF/Hebel",
    "ARKK": "ARKK – ETF/Hebel",
    "ARKW": "ARKW – ETF/Hebel",
    "ARRY": "ARRY [Technology]",
    "ASRT": "ASRT [Healthcare]",
    "ASTC": "ASTC [Technology]",
    "ASTS": "ASTS [Technology]",
    "ATO": "ATO [Utilities]",
    "ATR": "ATR [Healthcare]",
    "AVAV": "AVAV [Industrials]",
    "AVB": "AVB [Real Estate]",
    "AVGO": "AVGO [Technology]",
    "AVY": "AVY [Consumer Cyclical]",
    "AWK": "AWK [Utilities]",
    "AXP": "AXP [Financial Services]",
    "BA": "BA [Industrials]",
    "BABA": "BABA [Consumer Cyclical]",
    "BAC": "BAC [Financial Services]",
    "BAL": "BAL – ETF/Hebel",
    "BALL": "BALL [Consumer Cyclical]",
    "BAX": "BAX [Healthcare]",
    "BB": "BB [Technology]",
    "BBH": "BBH – ETF/Hebel",
    "BCRX": "BCRX [Healthcare]",
    "BDX": "BDX [Healthcare]",
    "BE": "BE [Industrials]",
    "BEAM": "BEAM [Healthcare]",
    "BECN": "BECN – Growth",
    "BF-B": "BF-B – Defensiv",
    "BG": "BG [Consumer Defensive]",
    "BHVN": "BHVN [Healthcare]",
    "BIDU": "BIDU [Communication Services]",
    "BIIB": "BIIB [Healthcare]",
    "BIOC": "BIOC – Spekulativ",
    "BITB": "BITB – ETF/Hebel",
    "BITO": "BITO – ETF/Hebel",
    "BKNG": "BKNG [Consumer Cyclical]",
    "BLBD": "BLBD [Industrials]",
    "BLD": "BLD [Industrials]",
    "BLK": "BLK [Financial Services]",
    "BMY": "BMY [Healthcare]",
    "BND": "BND – ETF/Hebel",
    "BNKU": "BNKU – ETF/Hebel",
    "BOIL": "BOIL – ETF/Hebel",
    "BOTZ": "BOTZ – ETF/Hebel",
    "BOX": "BOX [Technology]",
    "BRK-B": "BRK-B – Large-Cap",
    "BRO": "BRO [Financial Services]",
    "BROS": "BROS [Consumer Cyclical]",
    "BSX": "BSX [Healthcare]",
    "BTBT": "BTBT [Financial Services]",
    "BTCI": "BTCI – ETF/Hebel",
    "BURL": "BURL [Consumer Cyclical]",
    "BWXT": "BWXT [Industrials]",
    "BXP": "BXP [Real Estate]",
    "C": "C [Financial Services]",
    "CABO": "CABO [Communication Services]",
    "CAFE": "CAFE – ETF/Hebel",
    "CAG": "CAG [Consumer Defensive]",
    "CALM": "CALM [Consumer Defensive]",
    "CAN": "CAN [Technology]",
    "CARR": "CARR [Industrials]",
    "CAT": "CAT [Industrials]",
    "CB": "CB [Financial Services]",
    "CBOE": "CBOE [Financial Services]",
    "CCI": "CCI [Real Estate]",
    "CCK": "CCK [Consumer Cyclical]",
    "CDNS": "CDNS [Technology]",
    "CENX": "CENX [Basic Materials]",
    "CERT": "CERT [Healthcare]",
    "CGC": "CGC [Healthcare]",
    "CHD": "CHD [Consumer Defensive]",
    "CHKP": "CHKP [Technology]",
    "CHRW": "CHRW [Industrials]",
    "CHTR": "CHTR [Communication Services]",
    "CHWY": "CHWY [Consumer Cyclical]",
    "CI": "CI [Healthcare]",
    "CIBR": "CIBR – ETF/Hebel",
    "CIFR": "CIFR [Technology]",
    "CINF": "CINF [Financial Services]",
    "CL": "CL [Consumer Defensive]",
    "CLF": "CLF [Basic Materials]",
    "CLOU": "CLOU – ETF/Hebel",
    "CLSK": "CLSK [Financial Services]",
    "CMCSA": "CMCSA [Communication Services]",
    "CME": "CME [Financial Services]",
    "CMG": "CMG [Consumer Cyclical]",
    "CMS": "CMS [Utilities]",
    "CNI": "CNI [Industrials]",
    "CNP": "CNP [Utilities]",
    "COF": "COF [Financial Services]",
    "COIN": "COIN [Financial Services]",
    "COL": "COL – Large-Cap",
    "COO": "COO [Healthcare]",
    "CORN": "CORN – ETF/Hebel",
    "CORZ": "CORZ [Technology]",
    "COST": "COST [Consumer Defensive]",
    "COTY": "COTY [Consumer Defensive]",
    "COW": "COW – ETF/Hebel",
    "CP": "CP [Industrials]",
    "CPB": "CPB [Consumer Defensive]",
    "CPER": "CPER – ETF/Hebel",
    "CPT": "CPT [Real Estate]",
    "CRBU": "CRBU [Healthcare]",
    "CRLBF": "CRLBF [Healthcare]",
    "CRON": "CRON [Healthcare]",
    "CROX": "CROX [Consumer Cyclical]",
    "CRSP": "CRSP [Healthcare]",
    "CRSR": "CRSR [Technology]",
    "CRWD": "CRWD [Technology]",
    "CSCO": "CSCO [Technology]",
    "CSX": "CSX [Industrials]",
    "CTSH": "CTSH [Technology]",
    "CUBE": "CUBE [Real Estate]",
    "CVM": "CVM [Healthcare]",
    "CVS": "CVS [Healthcare]",
    "D": "D [Utilities]",
    "DASH": "DASH [Consumer Cyclical]",
    "DBA": "DBA – ETF/Hebel",
    "DD": "DD [Basic Materials]",
    "DDOG": "DDOG [Technology]",
    "DDS": "DDS [Consumer Cyclical]",
    "DE": "DE [Industrials]",
    "DEO": "DEO [Consumer Defensive]",
    "DG": "DG [Consumer Defensive]",
    "DGRO": "DGRO – ETF/Hebel",
    "DHI": "DHI [Consumer Cyclical]",
    "DHR": "DHR [Healthcare]",
    "DIA": "DIA – ETF/Hebel",
    "DKNG": "DKNG [Consumer Cyclical]",
    "DLO": "DLO [Technology]",
    "DLR": "DLR [Real Estate]",
    "DLTR": "DLTR [Consumer Defensive]",
    "DNLI": "DNLI [Healthcare]",
    "DOCU": "DOCU [Technology]",
    "DOMO": "DOMO [Technology]",
    "DOV": "DOV [Industrials]",
    "DOW": "DOW [Basic Materials]",
    "DPST": "DPST – ETF/Hebel",
    "DPZ": "DPZ [Consumer Cyclical]",
    "DRIV": "DRIV – ETF/Hebel",
    "DRN": "DRN – ETF/Hebel",
    "DRV": "DRV – ETF/Hebel",
    "DT": "DT [Technology]",
    "DUK": "DUK [Utilities]",
    "DUST": "DUST – ETF/Hebel",
    "DVN": "DVN – ETF/Hebel",
    "DVY": "DVY – ETF/Hebel",
    "DXCM": "DXCM [Healthcare]",
    "ECH": "ECH – ETF/Hebel",
    "ECL": "ECL [Basic Materials]",
    "ED": "ED [Utilities]",
    "EDIT": "EDIT [Healthcare]",
    "EDZ": "EDZ – ETF/Hebel",
    "EEM": "EEM – ETF/Hebel",
    "EFA": "EFA – ETF/Hebel",
    "EH": "EH [Industrials]",
    "EIDO": "EIDO – ETF/Hebel",
    "EIX": "EIX [Utilities]",
    "ELS": "ELS [Real Estate]",
    "ELV": "ELV – Defensiv",
    "EMR": "EMR [Industrials]",
    "ENPH": "ENPH [Technology]",
    "EPAM": "EPAM [Technology]",
    "EPI": "EPI – ETF/Hebel",
    "EQIX": "EQIX [Real Estate]",
    "EQR": "EQR [Real Estate]",
    "ES": "ES [Utilities]",
    "ESS": "ESS [Real Estate]",
    "ESTC": "ESTC [Technology]",
    "ETHA": "ETHA – ETF/Hebel",
    "ETHU": "ETHU – ETF/Hebel",
    "ETN": "ETN [Industrials]",
    "ETR": "ETR [Utilities]",
    "EVRG": "EVRG [Utilities]",
    "EW": "EW [Healthcare]",
    "EWA": "EWA – ETF/Hebel",
    "EWG": "EWG – ETF/Hebel",
    "EWJ": "EWJ – ETF/Hebel",
    "EWL": "EWL – ETF/Hebel",
    "EWQ": "EWQ – ETF/Hebel",
    "EWU": "EWU – ETF/Hebel",
    "EWZ": "EWZ – ETF/Hebel",
    "EXC": "EXC [Utilities]",
    "EXEL": "EXEL [Healthcare]",
    "EXP": "EXP [Basic Materials]",
    "EXPD": "EXPD [Industrials]",
    "EXPE": "EXPE [Consumer Cyclical]",
    "EXR": "EXR [Real Estate]",
    "FAS": "FAS – ETF/Hebel",
    "FATE": "FATE [Healthcare]",
    "FBTC": "FBTC – ETF/Hebel",
    "FCEL": "FCEL [Industrials]",
    "FCX": "FCX [Basic Materials]",
    "FDX": "FDX [Industrials]",
    "FE": "FE [Utilities]",
    "FHLC": "FHLC – ETF/Hebel",
    "FICO": "FICO [Technology]",
    "FIGS": "FIGS [Consumer Cyclical]",
    "FINX": "FINX – ETF/Hebel",
    "FIPDX": "FIPDX – ETF/Hebel",
    "FIX": "FIX [Industrials]",
    "FLCH": "FLCH – ETF/Hebel",
    "FLTR": "FLTR – Spekulativ",
    "FND": "FND [Consumer Cyclical]",
    "FNGD": "FNGD – ETF/Hebel",
    "FNGU": "FNGU – ETF/Hebel",
    "FNV": "FNV [Basic Materials]",
    "FREL": "FREL – ETF/Hebel",
    "FRT": "FRT [Real Estate]",
    "FTNT": "FTNT [Technology]",
    "FUBO": "FUBO [Communication Services]",
    "FXI": "FXI – ETF/Hebel",
    "GBTC": "GBTC – ETF/Hebel",
    "GD": "GD [Industrials]",
    "GDX": "GDX – ETF/Hebel",
    "GDXJ": "GDXJ – ETF/Hebel",
    "GE": "GE [Industrials]",
    "GEO": "GEO [Industrials]",
    "GGR": "GGR [Consumer Cyclical]",
    "GH": "GH [Healthcare]",
    "GILD": "GILD [Healthcare]",
    "GIS": "GIS [Consumer Defensive]",
    "GLD": "GLD – ETF/Hebel",
    "GLL": "GLL – ETF/Hebel",
    "GLPI": "GLPI [Real Estate]",
    "GME": "GME [Consumer Cyclical]",
    "GOLD": "GOLD [Financial Services]",
    "GOOGL": "GOOGL [Communication Services]",
    "GPK": "GPK [Consumer Cyclical]",
    "GPRO": "GPRO [Technology]",
    "GS": "GS [Financial Services]",
    "GSAT": "GSAT [Communication Services]",
    "GTBIF": "GTBIF [Healthcare]",
    "GTLB": "GTLB [Technology]",
    "HACK": "HACK – ETF/Hebel",
    "HALO": "HALO [Healthcare]",
    "HD": "HD [Consumer Cyclical]",
    "HDV": "HDV – ETF/Hebel",
    "HE": "HE [Utilities]",
    "HEAR": "HEAR – Spekulativ",
    "HEI": "HEI [Industrials]",
    "HIG": "HIG [Financial Services]",
    "HII": "HII [Industrials]",
    "HIVE": "HIVE [Financial Services]",
    "HLTH": "HLTH – Spekulativ",
    "HON": "HON [Industrials]",
    "HOOD": "HOOD [Financial Services]",
    "HRL": "HRL [Consumer Defensive]",
    "HSY": "HSY [Consumer Defensive]",
    "HUM": "HUM [Healthcare]",
    "HWM": "HWM [Industrials]",
    "HYG": "HYG – ETF/Hebel",
    "HYLN": "HYLN [Consumer Cyclical]",
    "IBB": "IBB – ETF/Hebel",
    "IBIT": "IBIT – ETF/Hebel",
    "IBKR": "IBKR [Financial Services]",
    "IBM": "IBM [Technology]",
    "ICE": "ICE [Financial Services]",
    "ICLN": "ICLN – ETF/Hebel",
    "IDA": "IDA [Utilities]",
    "IEF": "IEF – ETF/Hebel",
    "IHF": "IHF – ETF/Hebel",
    "IJR": "IJR – ETF/Hebel",
    "ILMN": "ILMN [Healthcare]",
    "IMRX": "IMRX [Healthcare]",
    "INCY": "INCY [Healthcare]",
    "INDA": "INDA – ETF/Hebel",
    "INFY": "INFY [Technology]",
    "INTC": "INTC [Technology]",
    "INTU": "INTU [Technology]",
    "INVH": "INVH [Real Estate]",
    "IP": "IP [Consumer Cyclical]",
    "IR": "IR [Industrials]",
    "IRDM": "IRDM [Communication Services]",
    "IREN": "IREN [Financial Services]",
    "ISRG": "ISRG [Healthcare]",
    "ITW": "ITW [Industrials]",
    "IVV": "IVV – ETF/Hebel",
    "IWM": "IWM – ETF/Hebel",
    "IYH": "IYH – ETF/Hebel",
    "IYR": "IYR – ETF/Hebel",
    "JAGX": "JAGX [Healthcare]",
    "JBHT": "JBHT [Industrials]",
    "JCI": "JCI [Industrials]",
    "JD": "JD [Consumer Cyclical]",
    "JDST": "JDST – ETF/Hebel",
    "JKS": "JKS [Technology]",
    "JNJ": "JNJ [Healthcare]",
    "JNK": "JNK – ETF/Hebel",
    "JNUG": "JNUG – ETF/Hebel",
    "JO": "JO – ETF/Hebel",
    "JOBY": "JOBY [Industrials]",
    "JPM": "JPM [Financial Services]",
    "K": "K – Defensiv",
    "KBH": "KBH [Consumer Cyclical]",
    "KGC": "KGC [Basic Materials]",
    "KHC": "KHC [Consumer Defensive]",
    "KIM": "KIM [Real Estate]",
    "KLAC": "KLAC [Technology]",
    "KMB": "KMB [Consumer Defensive]",
    "KO": "KO [Consumer Defensive]",
    "KOLD": "KOLD – ETF/Hebel",
    "KOSS": "KOSS [Technology]",
    "KR": "KR [Consumer Defensive]",
    "KSS": "KSS [Consumer Cyclical]",
    "KTOS": "KTOS [Industrials]",
    "KWEB": "KWEB – ETF/Hebel",
    "LABU": "LABU – ETF/Hebel",
    "LCID": "LCID [Consumer Cyclical]",
    "LDOS": "LDOS [Technology]",
    "LEN": "LEN [Consumer Cyclical]",
    "LGI": "LGI [Financial Services]",
    "LHX": "LHX [Industrials]",
    "LI": "LI [Consumer Cyclical]",
    "LIN": "LIN [Basic Materials]",
    "LIT": "LIT – ETF/Hebel",
    "LLY": "LLY [Healthcare]",
    "LMND": "LMND [Financial Services]",
    "LMT": "LMT [Industrials]",
    "LNT": "LNT [Utilities]",
    "LOGI": "LOGI [Technology]",
    "LOW": "LOW [Consumer Cyclical]",
    "LQD": "LQD – ETF/Hebel",
    "LRCX": "LRCX [Technology]",
    "LTPZ": "LTPZ – ETF/Hebel",
    "LUMN": "LUMN [Communication Services]",
    "LVGO": "LVGO – Spekulativ",
    "LYB": "LYB [Basic Materials]",
    "M": "M [Consumer Cyclical]",
    "MA": "MA [Financial Services]",
    "MAA": "MAA [Real Estate]",
    "MARA": "MARA [Financial Services]",
    "MCD": "MCD [Consumer Cyclical]",
    "MCHP": "MCHP [Technology]",
    "MCO": "MCO [Financial Services]",
    "MDA": "MDA [Industrials]",
    "MDB": "MDB [Technology]",
    "MDLZ": "MDLZ [Consumer Defensive]",
    "MDT": "MDT [Healthcare]",
    "MDY": "MDY – ETF/Hebel",
    "MELI": "MELI [Consumer Cyclical]",
    "MET": "MET [Financial Services]",
    "META": "META [Communication Services]",
    "MGNX": "MGNX [Healthcare]",
    "MILN": "MILN – ETF/Hebel",
    "MKC": "MKC [Consumer Defensive]",
    "MKTX": "MKTX [Financial Services]",
    "MLM": "MLM [Basic Materials]",
    "MMC": "MMC – Large-Cap",
    "MMM": "MMM [Industrials]",
    "MMYT": "MMYT [Consumer Cyclical]",
    "MRK": "MRK [Healthcare]",
    "MRNA": "MRNA [Healthcare]",
    "MS": "MS [Financial Services]",
    "MSFT": "MSFT [Technology]",
    "MTH": "MTH [Consumer Cyclical]",
    "MTTR": "MTTR – Spekulativ",
    "MU": "MU [Technology]",
    "MUB": "MUB – ETF/Hebel",
    "MVST": "MVST [Consumer Cyclical]",
    "NAIL": "NAIL – ETF/Hebel",
    "NDAQ": "NDAQ [Financial Services]",
    "NEE": "NEE [Utilities]",
    "NEM": "NEM [Basic Materials]",
    "NET": "NET [Technology]",
    "NIB": "NIB – ETF/Hebel",
    "NIBE": "NIBE – Spekulativ",
    "NIO": "NIO [Consumer Cyclical]",
    "NKE": "NKE [Consumer Cyclical]",
    "NLR": "NLR – ETF/Hebel",
    "NNN": "NNN [Real Estate]",
    "NNOX": "NNOX [Healthcare]",
    "NOC": "NOC [Industrials]",
    "NOW": "NOW [Technology]",
    "NRGU": "NRGU – ETF/Hebel",
    "NSC": "NSC [Industrials]",
    "NTLA": "NTLA [Healthcare]",
    "NU": "NU [Financial Services]",
    "NUE": "NUE [Basic Materials]",
    "NVDA": "NVDA [Technology]",
    "NVR": "NVR [Consumer Cyclical]",
    "NWE": "NWE [Utilities]",
    "NXPI": "NXPI [Technology]",
    "O": "O [Real Estate]",
    "ODFL": "ODFL [Industrials]",
    "OKTA": "OKTA [Technology]",
    "ONEM": "ONEM – Spekulativ",
    "ORCL": "ORCL [Technology]",
    "OTIS": "OTIS [Industrials]",
    "OTTR": "OTTR [Industrials]",
    "PANW": "PANW [Technology]",
    "PATH": "PATH [Technology]",
    "PBW": "PBW – ETF/Hebel",
    "PEG": "PEG [Utilities]",
    "PENN": "PENN [Consumer Cyclical]",
    "PEP": "PEP [Consumer Defensive]",
    "PEY": "PEY – ETF/Hebel",
    "PFE": "PFE [Healthcare]",
    "PG": "PG [Consumer Defensive]",
    "PGR": "PGR [Financial Services]",
    "PH": "PH [Industrials]",
    "PHM": "PHM [Consumer Cyclical]",
    "PICK": "PICK – ETF/Hebel",
    "PINS": "PINS [Communication Services]",
    "PJP": "PJP – ETF/Hebel",
    "PLD": "PLD [Real Estate]",
    "PLNHF": "PLNHF – Spekulativ",
    "PLTR": "PLTR [Technology]",
    "PLUG": "PLUG [Industrials]",
    "PNW": "PNW [Utilities]",
    "PODD": "PODD [Healthcare]",
    "POR": "POR [Utilities]",
    "PPG": "PPG [Basic Materials]",
    "PPH": "PPH – ETF/Hebel",
    "PPL": "PPL [Utilities]",
    "PRME": "PRME [Healthcare]",
    "PRTA": "PRTA [Healthcare]",
    "PRU": "PRU [Financial Services]",
    "PRVA": "PRVA [Healthcare]",
    "PSA": "PSA [Real Estate]",
    "PSNY": "PSNY [Consumer Cyclical]",
    "PYPL": "PYPL [Financial Services]",
    "QCOM": "QCOM [Technology]",
    "QQQ": "QQQ – ETF/Hebel",
    "QS": "QS [Consumer Cyclical]",
    "QSR": "QSR [Consumer Cyclical]",
    "RBLX": "RBLX [Communication Services]",
    "RDW": "RDW [Industrials]",
    "REET": "REET – ETF/Hebel",
    "REG": "REG [Real Estate]",
    "REGN": "REGN [Healthcare]",
    "RELY": "RELY [Technology]",
    "REMX": "REMX – ETF/Hebel",
    "REZ": "REZ – ETF/Hebel",
    "RGLD": "RGLD [Basic Materials]",
    "RIOT": "RIOT [Financial Services]",
    "RIVN": "RIVN [Consumer Cyclical]",
    "RKLB": "RKLB [Industrials]",
    "RMD": "RMD [Healthcare]",
    "ROBT": "ROBT – ETF/Hebel",
    "ROK": "ROK [Industrials]",
    "ROKU": "ROKU [Communication Services]",
    "ROOF": "ROOF – ETF/Hebel",
    "ROP": "ROP [Technology]",
    "ROST": "ROST [Consumer Cyclical]",
    "RSG": "RSG [Industrials]",
    "RSX": "RSX – ETF/Hebel",
    "RTX": "RTX [Industrials]",
    "RUN": "RUN [Technology]",
    "RWR": "RWR – ETF/Hebel",
    "SAIC": "SAIC [Technology]",
    "SBAC": "SBAC [Real Estate]",
    "SBUX": "SBUX [Consumer Cyclical]",
    "SCCO": "SCCO [Basic Materials]",
    "SCHD": "SCHD – ETF/Hebel",
    "SCHH": "SCHH – ETF/Hebel",
    "SCHP": "SCHP – ETF/Hebel",
    "SCHW": "SCHW [Financial Services]",
    "SCO": "SCO – ETF/Hebel",
    "SDIV": "SDIV – ETF/Hebel",
    "SDOW": "SDOW – ETF/Hebel",
    "SE": "SE [Consumer Cyclical]",
    "SEDG": "SEDG [Technology]",
    "SENS": "SENS [Healthcare]",
    "SES": "SES [Consumer Cyclical]",
    "SESN": "SESN – Spekulativ",
    "SGRY": "SGRY [Healthcare]",
    "SHAK": "SHAK [Consumer Cyclical]",
    "SHOP": "SHOP [Technology]",
    "SHW": "SHW [Basic Materials]",
    "SHY": "SHY – ETF/Hebel",
    "SJM": "SJM [Consumer Defensive]",
    "SKYY": "SKYY – ETF/Hebel",
    "SLDP": "SLDP [Consumer Cyclical]",
    "SLGN": "SLGN [Consumer Cyclical]",
    "SLV": "SLV – ETF/Hebel",
    "SMH": "SMH – ETF/Hebel",
    "SNAP": "SNAP [Communication Services]",
    "SNDL": "SNDL [Consumer Defensive]",
    "SNPS": "SNPS [Technology]",
    "SO": "SO [Utilities]",
    "SOFI": "SOFI [Financial Services]",
    "SOXL": "SOXL – ETF/Hebel",
    "SOXS": "SOXS – ETF/Hebel",
    "SOYB": "SOYB – ETF/Hebel",
    "SPCE": "SPCE [Industrials]",
    "SPG": "SPG [Real Estate]",
    "SPGI": "SPGI [Financial Services]",
    "SPXS": "SPXS – ETF/Hebel",
    "SPXU": "SPXU – ETF/Hebel",
    "SPY": "SPY – ETF/Hebel",
    "SPYD": "SPYD – ETF/Hebel",
    "SQQQ": "SQQQ – ETF/Hebel",
    "SRE": "SRE [Utilities]",
    "SRET": "SRET – ETF/Hebel",
    "SRPT": "SRPT [Healthcare]",
    "SRTY": "SRTY – ETF/Hebel",
    "STE": "STE [Healthcare]",
    "STIP": "STIP – ETF/Hebel",
    "STLD": "STLD [Basic Materials]",
    "STM": "STM [Technology]",
    "STNE": "STNE [Technology]",
    "SUI": "SUI [Real Estate]",
    "SUM": "SUM – Growth",
    "SVXY": "SVXY – ETF/Hebel",
    "SWKS": "SWKS [Technology]",
    "SYF": "SYF [Financial Services]",
    "SYK": "SYK [Healthcare]",
    "SYY": "SYY [Consumer Defensive]",
    "T": "T [Communication Services]",
    "TAN": "TAN – ETF/Hebel",
    "TCOM": "TCOM [Consumer Cyclical]",
    "TDG": "TDG [Industrials]",
    "TDOC": "TDOC [Healthcare]",
    "TEAM": "TEAM [Technology]",
    "TECL": "TECL – ETF/Hebel",
    "TFI": "TFI – ETF/Hebel",
    "TFX": "TFX [Healthcare]",
    "TGT": "TGT [Consumer Defensive]",
    "TIPS": "TIPS – ETF/Hebel",
    "TJX": "TJX [Consumer Cyclical]",
    "TLRY": "TLRY [Healthcare]",
    "TLT": "TLT – ETF/Hebel",
    "TME": "TME [Communication Services]",
    "TMO": "TMO [Healthcare]",
    "TMUS": "TMUS [Communication Services]",
    "TNDM": "TNDM [Healthcare]",
    "TOL": "TOL [Consumer Cyclical]",
    "TPIC": "TPIC – Spekulativ",
    "TQQQ": "TQQQ – ETF/Hebel",
    "TREE": "TREE [Financial Services]",
    "TREX": "TREX [Industrials]",
    "TRIP": "TRIP [Consumer Cyclical]",
    "TRV": "TRV [Financial Services]",
    "TSN": "TSN [Consumer Defensive]",
    "TT": "TT [Industrials]",
    "TUR": "TUR – ETF/Hebel",
    "TXN": "TXN [Technology]",
    "TXRH": "TXRH [Consumer Cyclical]",
    "TXT": "TXT [Industrials]",
    "TZA": "TZA – ETF/Hebel",
    "U": "U [Technology]",
    "UBER": "UBER [Technology]",
    "UBOT": "UBOT – ETF/Hebel",
    "UCO": "UCO – ETF/Hebel",
    "UDOW": "UDOW – ETF/Hebel",
    "UDR": "UDR [Real Estate]",
    "UMDD": "UMDD – ETF/Hebel",
    "UNG": "UNG – ETF/Hebel",
    "UNH": "UNH [Healthcare]",
    "UNP": "UNP [Industrials]",
    "UPRO": "UPRO – ETF/Hebel",
    "UPS": "UPS [Industrials]",
    "UPST": "UPST [Financial Services]",
    "URA": "URA – ETF/Hebel",
    "URBN": "URBN [Consumer Cyclical]",
    "USLV": "USLV – ETF/Hebel",
    "USO": "USO – ETF/Hebel",
    "UTHR": "UTHR [Healthcare]",
    "UVXY": "UVXY – ETF/Hebel",
    "UWMC": "UWMC [Financial Services]",
    "V": "V [Financial Services]",
    "VAW": "VAW – ETF/Hebel",
    "VB": "VB – ETF/Hebel",
    "VCR": "VCR – ETF/Hebel",
    "VDC": "VDC – ETF/Hebel",
    "VDE": "VDE – ETF/Hebel",
    "VEA": "VEA – ETF/Hebel",
    "VFF": "VFF [Consumer Defensive]",
    "VFH": "VFH – ETF/Hebel",
    "VGT": "VGT – ETF/Hebel",
    "VHT": "VHT – ETF/Hebel",
    "VIG": "VIG – ETF/Hebel",
    "VIPS": "VIPS [Consumer Cyclical]",
    "VIS": "VIS – ETF/Hebel",
    "VIXM": "VIXM – ETF/Hebel",
    "VIXY": "VIXY – ETF/Hebel",
    "VMC": "VMC [Basic Materials]",
    "VNQ": "VNQ – ETF/Hebel",
    "VO": "VO – ETF/Hebel",
    "VOO": "VOO – ETF/Hebel",
    "VPU": "VPU – ETF/Hebel",
    "VRSN": "VRSN [Technology]",
    "VRTX": "VRTX [Healthcare]",
    "VT": "VT – ETF/Hebel",
    "VTI": "VTI – ETF/Hebel",
    "VTIP": "VTIP – ETF/Hebel",
    "VWO": "VWO – ETF/Hebel",
    "VXRT": "VXRT [Healthcare]",
    "VXX": "VXX – ETF/Hebel",
    "VXZ": "VXZ – ETF/Hebel",
    "VYM": "VYM – ETF/Hebel",
    "VZ": "VZ [Communication Services]",
    "WATER": "WATER – ETF/Hebel",
    "WB": "WB [Communication Services]",
    "WCN": "WCN [Industrials]",
    "WDAY": "WDAY [Technology]",
    "WEAT": "WEAT – ETF/Hebel",
    "WEBL": "WEBL – ETF/Hebel",
    "WEC": "WEC [Utilities]",
    "WELL": "WELL [Real Estate]",
    "WFC": "WFC [Financial Services]",
    "WING": "WING [Consumer Cyclical]",
    "WIP": "WIP – ETF/Hebel",
    "WIT": "WIT [Technology]",
    "WK": "WK [Technology]",
    "WKHS": "WKHS [Consumer Cyclical]",
    "WM": "WM [Industrials]",
    "WMT": "WMT [Consumer Defensive]",
    "WPC": "WPC [Real Estate]",
    "WPM": "WPM [Basic Materials]",
    "WST": "WST [Healthcare]",
    "WTW": "WTW [Financial Services]",
    "WULF": "WULF [Financial Services]",
    "WWD": "WWD [Industrials]",
    "X": "X – Large-Cap",
    "XBI": "XBI – ETF/Hebel",
    "XEL": "XEL [Utilities]",
    "XLB": "XLB – ETF/Hebel",
    "XLC": "XLC – ETF/Hebel",
    "XLE": "XLE – ETF/Hebel",
    "XLF": "XLF – ETF/Hebel",
    "XLI": "XLI – ETF/Hebel",
    "XLK": "XLK – ETF/Hebel",
    "XLP": "XLP – ETF/Hebel",
    "XLRE": "XLRE – ETF/Hebel",
    "XLU": "XLU – ETF/Hebel",
    "XLV": "XLV – ETF/Hebel",
    "XLY": "XLY – ETF/Hebel",
    "XME": "XME – ETF/Hebel",
    "XPEV": "XPEV [Consumer Cyclical]",
    "XPO": "XPO [Industrials]",
    "XSD": "XSD – ETF/Hebel",
    "XYZ": "XYZ – Large-Cap",
    "YI": "YI [Healthcare]",
    "YUM": "YUM [Consumer Cyclical]",
    "ZBH": "ZBH [Healthcare]",
    "ZIV": "ZIV – ETF/Hebel",
    "ZM": "ZM [Technology]",
    "ZS": "ZS [Technology]",
    "ZSL": "ZSL – ETF/Hebel",
}

# ─── Risk-Stufen ──────────────────────────────────────────────
RISK_STUFEN = list(range(0, 100, 5))  # 0,5,10,…,95

def get_allowed_tiers(risk: int) -> list:
    """Welche Tiers für diese Risk-Stufe erlaubt sind."""
    if risk <= 10:
        return [0]
    elif risk <= 30:
        return [0, 1]
    elif risk <= 50:
        return [0, 1, 2]
    elif risk <= 70:
        return [0, 1, 2, 3]
    else:
        return [1, 2, 3, 4]

def get_params(risk: int) -> dict:
    """Risk→Parameter: Positionen, Größe, Stop-Loss, Take-Profit, Score-Grenzen."""
    # Dynamisch: defensiv → viele kleine Positionen, spekulativ → wenige große
    max_pos = max(4, min(8, 8 - (risk // 20)))  # 8 bei Risk 0 → 4 bei Risk 95 (viele kleine statt wenige teure)
    pos_size = 0.15 + (risk / 100) * 0.25  # 0.15 bei Risk 0 → 0.40 bei Risk 95 (kleinere Klumpen)
    min_score = max(25, 50 - (risk // 3))  # 50 bei Risk 0 → 25 bei Risk 95

    return {
        "max_positions": max_pos,
        "position_size": round(pos_size, 3),
        "stop_loss": max(0.85, 0.97 - (risk * 0.001)),  # 0.97→0.87
        "take_profit": min(1.30, 1.10 + (risk * 0.002)),  # 1.10→1.30
        "min_score": min_score,
    }


# ─── Alias für Abwärtskompatibilität ───────────────────────────
fuer_risk_stufe = get_params

if __name__ == "__main__":
    print("Risk Profile – Validierung")
    for t in range(5):
        print(f"  Tier {t}: {len(TIERS[t])} tickers")
    print(f"  Total: {sum(len(v) for v in TIERS.values())} tickers")
    print(f"  Ticker→Tier: {len(TICKER_TO_TIER)} mappings")
    print(f"  Names: {len(TICKER_NAMES)} entries")
    print()
    for risk in [0, 10, 25, 50, 75, 95]:
        p = get_params(risk)
        a = get_allowed_tiers(risk)
        print(f"  Risk {risk:3d}: allowed={a}  max_pos={p['max_positions']}  size={p['position_size']}  sl={p['stop_loss']}  tp={p['take_profit']}  min_score={p['min_score']}")