# risk_profile.py – automatisch generiert (664 Ticker, 22 tote entfernt)
# Nutzung: from risk_profile import TIERS, TICKER_TO_TIER, get_params

TIERS = {
    0: [
        "ABBV", "ABT", "ABX", "ACI", "ADM", "AEE", "AEP", "AGI", "ALC", "AMH", "AMT", "ARE",
        "ATO", "ATR", "AVB", "AWK", "BAX", "BDX", "BF-B", "BG", "BMY", "BSX", "BXP", "CAG",
        "CALM", "CCK", "CI", "CL", "CMS", "CNP", "COO", "COST", "COTY", "CPB", "CPT", "CUBE",
        "CVS", "D", "DEO", "DG", "DHR", "DLR", "DLTR", "DUK", "DXCM", "ED", "EIX", "ELS",
        "ELV", "EQIX", "EQR", "ES", "ESS", "ETR", "EVRG", "EW", "EXC", "EXR", "FE", "FNV",
        "FRT", "GIS", "GOLD", "GPK", "HE", "HRL", "HSY", "HUM", "IDA", "INVH", "IP", "ISRG",
        "JNJ", "KGC", "KHC", "KIM", "KMB", "KO", "KR", "LLY", "LNT", "MAA", "MDLZ", "MDT",
        "MKC", "MRK", "NEE", "NEM", "NNN", "NWE", "O", "OTTR", "PEG", "PEP", "PFE", "PG",
        "PLD", "PNW", "POR", "PPL", "PSA", "REG", "RGLD", "RMD", "SJM", "SO", "SPG", "SRE",
        "SUI", "SYK", "SYY", "TFX", "TGT", "TMO", "TSN", "UDR", "UNH", "WEC", "WELL", "WMT",
        "WPC", "WPM", "WST", "XEL", "ZBH",
    ],
    1: [
        "AA", "AAPL", "ADI", "AFL", "AJG", "ALL", "AMAT", "AMD", "AME", "AMZN", "AON", "APD",
        "AVGO", "AVY", "AXP", "BA", "BAC", "BALL", "BLK", "BRK-B", "BRO", "BWXT", "C", "CABO",
        "CARR", "CAT", "CB", "CBOE", "CCI", "CDNS", "CENX", "CHD", "CHRW", "CHTR", "CINF", "CLF",
        "CMCSA", "CME", "CNI", "COF", "CP", "CROX", "CSCO", "CSX", "DD", "DE", "DOV", "DOW",
        "ECL", "EMR", "ETN", "EXPD", "FCX", "FDX", "GD", "GE", "GOOGL", "GS", "HIG", "HII",
        "HON", "HWM", "IBKR", "IBM", "ICE", "INTC", "IR", "ITW", "JBHT", "JCI", "JPM", "KLAC",
        "LDOS", "LHX", "LIN", "LMT", "LRCX", "LUMN", "LYB", "MA", "MCHP", "MCO", "MET", "META",
        "MKTX", "MMM", "MS", "MSFT", "MU", "NDAQ", "NOC", "NSC", "NUE", "NVDA", "NXPI", "ODFL",
        "ORCL", "OTIS", "PGR", "PH", "PPG", "PRU", "PYPL", "QCOM", "ROK", "ROP", "RSG", "RTX",
        "SAIC", "SBAC", "SCCO", "SCHW", "SHW", "SLGN", "SNPS", "SPGI", "STE", "STLD", "STM", "SWKS",
        "SYF", "T", "TDG", "TMUS", "TRV", "TT", "TXN", "TXT", "UNP", "UPS", "V", "VZ",
        "WCN", "WFC", "WM", "WTW", "XPO", "XYZ",
    ],
    2: [
        "ABNB", "ACN", "ADSK", "AEO", "AI", "ALGN", "ALKS", "ALNY", "AMGN", "ANF", "ARRY", "AVAV",
        "BE", "BHVN", "BIIB", "BKNG", "BLD", "BOX", "BURL", "CHKP", "CMG", "COIN", "CRWD", "CTSH",
        "DASH", "DDOG", "DDS", "DHI", "DOCU", "DOMO", "DPZ", "DT", "ENPH", "EPAM", "ESTC", "EXEL",
        "EXP", "EXPE", "FCEL", "FICO", "FIX", "FND", "FTNT", "GH", "GILD", "GLPI", "GTLB", "HALO",
        "HD", "HEI", "ILMN", "INCY", "INFY", "INTU", "JKS", "KBH", "KSS", "KTOS", "LEN", "LGI",
        "LOW", "M", "MCD", "MDB", "MGNX", "MLM", "MMYT", "MRNA", "MTH", "NET", "NKE", "NOW",
        "NVR", "OKTA", "PANW", "PATH", "PHM", "PINS", "PLTR", "PLUG", "PODD", "PRVA", "QSR", "RBLX",
        "REGN", "ROKU", "ROST", "RUN", "SBUX", "SEDG", "SGRY", "SHAK", "SHOP", "SNAP", "SOFI", "SRPT",
        "TCOM", "TEAM", "TJX", "TNDM", "TOL", "TREX", "TRIP", "TXRH", "UBER", "URBN", "UTHR", "VMC",
        "VRSN", "VRTX", "WDAY", "WING", "WIT", "WK", "WWD", "YUM", "ZM", "ZS",
    ],
    3: [
        "ACB", "ACHR", "AEHR", "AFRM", "ALLO", "AMC", "ASRT", "ASTC", "ASTS", "BABA", "BB", "BCRX",
        "BEAM", "BIDU", "BLBD", "BROS", "BTBT", "CAN", "CERT", "CGC", "CHWY", "CIFR", "CLSK", "CORZ",
        "CRBU", "CRLBF", "CRON", "CRSP", "CRSR", "CVM", "DKNG", "DLO", "DNLI", "EDIT", "EH", "FATE",
        "FIGS", "FLTR", "FUBO", "GEO", "GGR", "GME", "GPRO", "GSAT", "GTBIF", "HIVE", "HLTH", "HOOD",
        "HYLN", "IMRX", "IRDM", "IREN", "JAGX", "JD", "JOBY", "KOSS", "LCID", "LI", "LMND", "LOGI",
        "MARA", "MDA", "MELI", "MVST", "NIO", "NNOX", "NTLA", "NU", "PENN", "PRME", "PRTA", "PSNY",
        "QS", "RDW", "RELY", "RIOT", "RIVN", "RKLB", "SE", "SENS", "SES", "SLDP", "SNDL", "SPCE",
        "STNE", "TDOC", "TLRY", "TME", "TPIC", "TREE", "U", "UPST", "UWMC", "VFF", "VIPS", "VXRT",
        "WB", "WKHS", "WULF", "XPEV", "YI",
    ],
    4: [
        "AGG", "AIQ", "ARKB", "ARKF", "ARKG", "ARKK", "ARKW", "BBH", "BITB", "BITO", "BND", "BNKU",
        "BOIL", "BOTZ", "BTCI", "CIBR", "CLOU", "CORN", "CPER", "DBA", "DGRO", "DIA", "DPST", "DRIV",
        "DRN", "DRV", "DUST", "DVN", "DVY", "ECH", "EDZ", "EEM", "EFA", "EIDO", "EPI", "ETHA",
        "ETHU", "EWA", "EWG", "EWJ", "EWL", "EWQ", "EWU", "EWZ", "FAS", "FBTC", "FHLC", "FINX",
        "FIPDX", "FLCH", "FNGD", "FNGU", "FREL", "FXI", "GBTC", "GDX", "GDXJ", "GLD", "GLL", "HACK",
        "HDV", "HYG", "IBB", "IBIT", "ICLN", "IEF", "IHF", "IJR", "INDA", "IVV", "IWM", "IYH",
        "IYR", "JDST", "JNK", "JNUG", "KOLD", "KWEB", "LABU", "LIT", "LQD", "LTPZ", "MDY", "MILN",
        "MUB", "NAIL", "NLR", "NRGU", "PBW", "PEY", "PICK", "PJP", "PPH", "QQQ", "REET", "REMX",
        "REZ", "ROBT", "RSX", "RWR", "SCHD", "SCHH", "SCHP", "SCO", "SDIV", "SDOW", "SHY", "SKYY",
        "SLV", "SMH", "SOXL", "SOXS", "SOYB", "SPXS", "SPXU", "SPY", "SPYD", "SQQQ", "SRET", "SRTY",
        "STIP", "SVXY", "TAN", "TECL", "TFI", "TIPS", "TLT", "TQQQ", "TUR", "TZA", "UBOT", "UCO",
        "UDOW", "UMDD", "UNG", "UPRO", "URA", "USLV", "USO", "UVXY", "VAW", "VB", "VCR", "VDC",
        "VDE", "VEA", "VFH", "VGT", "VHT", "VIG", "VIS", "VIXM", "VIXY", "VNQ", "VO", "VOO",
        "VPU", "VT", "VTI", "VTIP", "VWO", "VXX", "VXZ", "VYM", "WEAT", "WEBL", "WIP", "XBI",
        "XLB", "XLC", "XLE", "XLF", "XLI", "XLK", "XLP", "XLRE", "XLU", "XLV", "XLY", "XME",
        "XSD", "ZSL",
    ],
}

TICKER_TO_TIER = {
    "AA": 1,
    "AAPL": 1,
    "ABBV": 0,
    "ABNB": 2,
    "ABT": 0,
    "ABX": 0,
    "ACB": 3,
    "ACHR": 3,
    "ACI": 0,
    "ACN": 2,
    "ADI": 1,
    "ADM": 0,
    "ADSK": 2,
    "AEE": 0,
    "AEHR": 3,
    "AEO": 2,
    "AEP": 0,
    "AFL": 1,
    "AFRM": 3,
    "AGG": 4,
    "AGI": 0,
    "AI": 2,
    "AIQ": 4,
    "AJG": 1,
    "ALC": 0,
    "ALGN": 2,
    "ALKS": 2,
    "ALL": 1,
    "ALLO": 3,
    "ALNY": 2,
    "AMAT": 1,
    "AMC": 3,
    "AMD": 1,
    "AME": 1,
    "AMGN": 2,
    "AMH": 0,
    "AMT": 0,
    "AMZN": 1,
    "ANF": 2,
    "AON": 1,
    "APD": 1,
    "ARE": 0,
    "ARKB": 4,
    "ARKF": 4,
    "ARKG": 4,
    "ARKK": 4,
    "ARKW": 4,
    "ARRY": 2,
    "ASRT": 3,
    "ASTC": 3,
    "ASTS": 3,
    "ATO": 0,
    "ATR": 0,
    "AVAV": 2,
    "AVB": 0,
    "AVGO": 1,
    "AVY": 1,
    "AWK": 0,
    "AXP": 1,
    "BA": 1,
    "BABA": 3,
    "BAC": 1,
    "BALL": 1,
    "BAX": 0,
    "BB": 3,
    "BBH": 4,
    "BCRX": 3,
    "BDX": 0,
    "BE": 2,
    "BEAM": 3,
    "BF-B": 0,
    "BG": 0,
    "BHVN": 2,
    "BIDU": 3,
    "BIIB": 2,
    "BITB": 4,
    "BITO": 4,
    "BKNG": 2,
    "BLBD": 3,
    "BLD": 2,
    "BLK": 1,
    "BMY": 0,
    "BND": 4,
    "BNKU": 4,
    "BOIL": 4,
    "BOTZ": 4,
    "BOX": 2,
    "BRK-B": 1,
    "BRO": 1,
    "BROS": 3,
    "BSX": 0,
    "BTBT": 3,
    "BTCI": 4,
    "BURL": 2,
    "BWXT": 1,
    "BXP": 0,
    "C": 1,
    "CABO": 1,
    "CAG": 0,
    "CALM": 0,
    "CAN": 3,
    "CARR": 1,
    "CAT": 1,
    "CB": 1,
    "CBOE": 1,
    "CCI": 1,
    "CCK": 0,
    "CDNS": 1,
    "CENX": 1,
    "CERT": 3,
    "CGC": 3,
    "CHD": 1,
    "CHKP": 2,
    "CHRW": 1,
    "CHTR": 1,
    "CHWY": 3,
    "CI": 0,
    "CIBR": 4,
    "CIFR": 3,
    "CINF": 1,
    "CL": 0,
    "CLF": 1,
    "CLOU": 4,
    "CLSK": 3,
    "CMCSA": 1,
    "CME": 1,
    "CMG": 2,
    "CMS": 0,
    "CNI": 1,
    "CNP": 0,
    "COF": 1,
    "COIN": 2,
    "COO": 0,
    "CORN": 4,
    "CORZ": 3,
    "COST": 0,
    "COTY": 0,
    "CP": 1,
    "CPB": 0,
    "CPER": 4,
    "CPT": 0,
    "CRBU": 3,
    "CRLBF": 3,
    "CRON": 3,
    "CROX": 1,
    "CRSP": 3,
    "CRSR": 3,
    "CRWD": 2,
    "CSCO": 1,
    "CSX": 1,
    "CTSH": 2,
    "CUBE": 0,
    "CVM": 3,
    "CVS": 0,
    "D": 0,
    "DASH": 2,
    "DBA": 4,
    "DD": 1,
    "DDOG": 2,
    "DDS": 2,
    "DE": 1,
    "DEO": 0,
    "DG": 0,
    "DGRO": 4,
    "DHI": 2,
    "DHR": 0,
    "DIA": 4,
    "DKNG": 3,
    "DLO": 3,
    "DLR": 0,
    "DLTR": 0,
    "DNLI": 3,
    "DOCU": 2,
    "DOMO": 2,
    "DOV": 1,
    "DOW": 1,
    "DPST": 4,
    "DPZ": 2,
    "DRIV": 4,
    "DRN": 4,
    "DRV": 4,
    "DT": 2,
    "DUK": 0,
    "DUST": 4,
    "DVN": 4,
    "DVY": 4,
    "DXCM": 0,
    "ECH": 4,
    "ECL": 1,
    "ED": 0,
    "EDIT": 3,
    "EDZ": 4,
    "EEM": 4,
    "EFA": 4,
    "EH": 3,
    "EIDO": 4,
    "EIX": 0,
    "ELS": 0,
    "ELV": 0,
    "EMR": 1,
    "ENPH": 2,
    "EPAM": 2,
    "EPI": 4,
    "EQIX": 0,
    "EQR": 0,
    "ES": 0,
    "ESS": 0,
    "ESTC": 2,
    "ETHA": 4,
    "ETHU": 4,
    "ETN": 1,
    "ETR": 0,
    "EVRG": 0,
    "EW": 0,
    "EWA": 4,
    "EWG": 4,
    "EWJ": 4,
    "EWL": 4,
    "EWQ": 4,
    "EWU": 4,
    "EWZ": 4,
    "EXC": 0,
    "EXEL": 2,
    "EXP": 2,
    "EXPD": 1,
    "EXPE": 2,
    "EXR": 0,
    "FAS": 4,
    "FATE": 3,
    "FBTC": 4,
    "FCEL": 2,
    "FCX": 1,
    "FDX": 1,
    "FE": 0,
    "FHLC": 4,
    "FICO": 2,
    "FIGS": 3,
    "FINX": 4,
    "FIPDX": 4,
    "FIX": 2,
    "FLCH": 4,
    "FLTR": 3,
    "FND": 2,
    "FNGD": 4,
    "FNGU": 4,
    "FNV": 0,
    "FREL": 4,
    "FRT": 0,
    "FTNT": 2,
    "FUBO": 3,
    "FXI": 4,
    "GBTC": 4,
    "GD": 1,
    "GDX": 4,
    "GDXJ": 4,
    "GE": 1,
    "GEO": 3,
    "GGR": 3,
    "GH": 2,
    "GILD": 2,
    "GIS": 0,
    "GLD": 4,
    "GLL": 4,
    "GLPI": 2,
    "GME": 3,
    "GOLD": 0,
    "GOOGL": 1,
    "GPK": 0,
    "GPRO": 3,
    "GS": 1,
    "GSAT": 3,
    "GTBIF": 3,
    "GTLB": 2,
    "HACK": 4,
    "HALO": 2,
    "HD": 2,
    "HDV": 4,
    "HE": 0,
    "HEI": 2,
    "HIG": 1,
    "HII": 1,
    "HIVE": 3,
    "HLTH": 3,
    "HON": 1,
    "HOOD": 3,
    "HRL": 0,
    "HSY": 0,
    "HUM": 0,
    "HWM": 1,
    "HYG": 4,
    "HYLN": 3,
    "IBB": 4,
    "IBIT": 4,
    "IBKR": 1,
    "IBM": 1,
    "ICE": 1,
    "ICLN": 4,
    "IDA": 0,
    "IEF": 4,
    "IHF": 4,
    "IJR": 4,
    "ILMN": 2,
    "IMRX": 3,
    "INCY": 2,
    "INDA": 4,
    "INFY": 2,
    "INTC": 1,
    "INTU": 2,
    "INVH": 0,
    "IP": 0,
    "IR": 1,
    "IRDM": 3,
    "IREN": 3,
    "ISRG": 0,
    "ITW": 1,
    "IVV": 4,
    "IWM": 4,
    "IYH": 4,
    "IYR": 4,
    "JAGX": 3,
    "JBHT": 1,
    "JCI": 1,
    "JD": 3,
    "JDST": 4,
    "JKS": 2,
    "JNJ": 0,
    "JNK": 4,
    "JNUG": 4,
    "JOBY": 3,
    "JPM": 1,
    "KBH": 2,
    "KGC": 0,
    "KHC": 0,
    "KIM": 0,
    "KLAC": 1,
    "KMB": 0,
    "KO": 0,
    "KOLD": 4,
    "KOSS": 3,
    "KR": 0,
    "KSS": 2,
    "KTOS": 2,
    "KWEB": 4,
    "LABU": 4,
    "LCID": 3,
    "LDOS": 1,
    "LEN": 2,
    "LGI": 2,
    "LHX": 1,
    "LI": 3,
    "LIN": 1,
    "LIT": 4,
    "LLY": 0,
    "LMND": 3,
    "LMT": 1,
    "LNT": 0,
    "LOGI": 3,
    "LOW": 2,
    "LQD": 4,
    "LRCX": 1,
    "LTPZ": 4,
    "LUMN": 1,
    "LYB": 1,
    "M": 2,
    "MA": 1,
    "MAA": 0,
    "MARA": 3,
    "MCD": 2,
    "MCHP": 1,
    "MCO": 1,
    "MDA": 3,
    "MDB": 2,
    "MDLZ": 0,
    "MDT": 0,
    "MDY": 4,
    "MELI": 3,
    "MET": 1,
    "META": 1,
    "MGNX": 2,
    "MILN": 4,
    "MKC": 0,
    "MKTX": 1,
    "MLM": 2,
    "MMM": 1,
    "MMYT": 2,
    "MRK": 0,
    "MRNA": 2,
    "MS": 1,
    "MSFT": 1,
    "MTH": 2,
    "MU": 1,
    "MUB": 4,
    "MVST": 3,
    "NAIL": 4,
    "NDAQ": 1,
    "NEE": 0,
    "NEM": 0,
    "NET": 2,
    "NIO": 3,
    "NKE": 2,
    "NLR": 4,
    "NNN": 0,
    "NNOX": 3,
    "NOC": 1,
    "NOW": 2,
    "NRGU": 4,
    "NSC": 1,
    "NTLA": 3,
    "NU": 3,
    "NUE": 1,
    "NVDA": 1,
    "NVR": 2,
    "NWE": 0,
    "NXPI": 1,
    "O": 0,
    "ODFL": 1,
    "OKTA": 2,
    "ORCL": 1,
    "OTIS": 1,
    "OTTR": 0,
    "PANW": 2,
    "PATH": 2,
    "PBW": 4,
    "PEG": 0,
    "PENN": 3,
    "PEP": 0,
    "PEY": 4,
    "PFE": 0,
    "PG": 0,
    "PGR": 1,
    "PH": 1,
    "PHM": 2,
    "PICK": 4,
    "PINS": 2,
    "PJP": 4,
    "PLD": 0,
    "PLTR": 2,
    "PLUG": 2,
    "PNW": 0,
    "PODD": 2,
    "POR": 0,
    "PPG": 1,
    "PPH": 4,
    "PPL": 0,
    "PRME": 3,
    "PRTA": 3,
    "PRU": 1,
    "PRVA": 2,
    "PSA": 0,
    "PSNY": 3,
    "PYPL": 1,
    "QCOM": 1,
    "QQQ": 4,
    "QS": 3,
    "QSR": 2,
    "RBLX": 2,
    "RDW": 3,
    "REET": 4,
    "REG": 0,
    "REGN": 2,
    "RELY": 3,
    "REMX": 4,
    "REZ": 4,
    "RGLD": 0,
    "RIOT": 3,
    "RIVN": 3,
    "RKLB": 3,
    "RMD": 0,
    "ROBT": 4,
    "ROK": 1,
    "ROKU": 2,
    "ROP": 1,
    "ROST": 2,
    "RSG": 1,
    "RSX": 4,
    "RTX": 1,
    "RUN": 2,
    "RWR": 4,
    "SAIC": 1,
    "SBAC": 1,
    "SBUX": 2,
    "SCCO": 1,
    "SCHD": 4,
    "SCHH": 4,
    "SCHP": 4,
    "SCHW": 1,
    "SCO": 4,
    "SDIV": 4,
    "SDOW": 4,
    "SE": 3,
    "SEDG": 2,
    "SENS": 3,
    "SES": 3,
    "SGRY": 2,
    "SHAK": 2,
    "SHOP": 2,
    "SHW": 1,
    "SHY": 4,
    "SJM": 0,
    "SKYY": 4,
    "SLDP": 3,
    "SLGN": 1,
    "SLV": 4,
    "SMH": 4,
    "SNAP": 2,
    "SNDL": 3,
    "SNPS": 1,
    "SO": 0,
    "SOFI": 2,
    "SOXL": 4,
    "SOXS": 4,
    "SOYB": 4,
    "SPCE": 3,
    "SPG": 0,
    "SPGI": 1,
    "SPXS": 4,
    "SPXU": 4,
    "SPY": 4,
    "SPYD": 4,
    "SQQQ": 4,
    "SRE": 0,
    "SRET": 4,
    "SRPT": 2,
    "SRTY": 4,
    "STE": 1,
    "STIP": 4,
    "STLD": 1,
    "STM": 1,
    "STNE": 3,
    "SUI": 0,
    "SVXY": 4,
    "SWKS": 1,
    "SYF": 1,
    "SYK": 0,
    "SYY": 0,
    "T": 1,
    "TAN": 4,
    "TCOM": 2,
    "TDG": 1,
    "TDOC": 3,
    "TEAM": 2,
    "TECL": 4,
    "TFI": 4,
    "TFX": 0,
    "TGT": 0,
    "TIPS": 4,
    "TJX": 2,
    "TLRY": 3,
    "TLT": 4,
    "TME": 3,
    "TMO": 0,
    "TMUS": 1,
    "TNDM": 2,
    "TOL": 2,
    "TPIC": 3,
    "TQQQ": 4,
    "TREE": 3,
    "TREX": 2,
    "TRIP": 2,
    "TRV": 1,
    "TSN": 0,
    "TT": 1,
    "TUR": 4,
    "TXN": 1,
    "TXRH": 2,
    "TXT": 1,
    "TZA": 4,
    "U": 3,
    "UBER": 2,
    "UBOT": 4,
    "UCO": 4,
    "UDOW": 4,
    "UDR": 0,
    "UMDD": 4,
    "UNG": 4,
    "UNH": 0,
    "UNP": 1,
    "UPRO": 4,
    "UPS": 1,
    "UPST": 3,
    "URA": 4,
    "URBN": 2,
    "USLV": 4,
    "USO": 4,
    "UTHR": 2,
    "UVXY": 4,
    "UWMC": 3,
    "V": 1,
    "VAW": 4,
    "VB": 4,
    "VCR": 4,
    "VDC": 4,
    "VDE": 4,
    "VEA": 4,
    "VFF": 3,
    "VFH": 4,
    "VGT": 4,
    "VHT": 4,
    "VIG": 4,
    "VIPS": 3,
    "VIS": 4,
    "VIXM": 4,
    "VIXY": 4,
    "VMC": 2,
    "VNQ": 4,
    "VO": 4,
    "VOO": 4,
    "VPU": 4,
    "VRSN": 2,
    "VRTX": 2,
    "VT": 4,
    "VTI": 4,
    "VTIP": 4,
    "VWO": 4,
    "VXRT": 3,
    "VXX": 4,
    "VXZ": 4,
    "VYM": 4,
    "VZ": 1,
    "WB": 3,
    "WCN": 1,
    "WDAY": 2,
    "WEAT": 4,
    "WEBL": 4,
    "WEC": 0,
    "WELL": 0,
    "WFC": 1,
    "WING": 2,
    "WIP": 4,
    "WIT": 2,
    "WK": 2,
    "WKHS": 3,
    "WM": 1,
    "WMT": 0,
    "WPC": 0,
    "WPM": 0,
    "WST": 0,
    "WTW": 1,
    "WULF": 3,
    "WWD": 2,
    "XBI": 4,
    "XEL": 0,
    "XLB": 4,
    "XLC": 4,
    "XLE": 4,
    "XLF": 4,
    "XLI": 4,
    "XLK": 4,
    "XLP": 4,
    "XLRE": 4,
    "XLU": 4,
    "XLV": 4,
    "XLY": 4,
    "XME": 4,
    "XPEV": 3,
    "XPO": 1,
    "XSD": 4,
    "XYZ": 1,
    "YI": 3,
    "YUM": 2,
    "ZBH": 0,
    "ZM": 2,
    "ZS": 2,
    "ZSL": 4,
}

def get_params(risk):
    """Liefert Risiko-Parameter für eine Risk-Stufe (0-95)."""
    TIER_BONUS = {0: 0, 1: 3, 2: 6, 3: 10, 4: 15}
    max_pos = 2 if risk >= 50 else 3 if risk >= 30 else 4 if risk >= 15 else 2 if risk >= 5 else 3
    # Risk-low: defensive Tiers, Risk-high: spekulative Tiers
    if risk <= 15:
        tiers = [0, 1, 2]
        base_bonus = {0: 10, 1: 5, 2: 0, 3: -5, 4: -10}
        min_score = 45
        stop_loss = 0.92
        take_profit = 1.12
        volatility_bonus = 3
    elif risk <= 40:
        tiers = [0, 1, 2, 3]
        base_bonus = {0: 5, 1: 3, 2: 0, 3: -3, 4: -5}
        min_score = 40
        stop_loss = 0.90
        take_profit = 1.15
        volatility_bonus = 5
    elif risk <= 70:
        tiers = [1, 2, 3]
        base_bonus = {0: -5, 1: 2, 2: 0, 3: -2, 4: -5}
        min_score = 30
        stop_loss = 0.88
        take_profit = 1.20
        volatility_bonus = 7
    else:
        tiers = [2, 3, 4]
        base_bonus = {0: -10, 1: -5, 2: 0, 3: 3, 4: 8}
        min_score = 25
        stop_loss = 0.85
        take_profit = 1.25
        volatility_bonus = 10
    pos_size = 0.60 if risk >= 50 else 0.40 if risk >= 15 else 0.30
    return {
        "allowed_tiers": tiers,
        "tier_bonus": base_bonus,
        "min_score": min_score,
        "stop_loss": stop_loss,
        "take_profit": take_profit,
        "volatility_bonus": volatility_bonus,
        "max_positions": max_pos,
        "position_size": pos_size,
    }

RISK_STUFEN = [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]
fuer_risk_stufe = get_params  # Alias
